import type { Metadata } from "next";
import { Abel, Montserrat, Orbitron, Saira, Urbanist } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets:["latin"],weight:["400","700","500"]})
const saira = Saira({ subsets:["latin"],weight:"400"});
const abel = Abel({ subsets:["latin"],weight:"400"});
const teko = Urbanist({ subsets:["latin"],weight:["400","700",]});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={saira.className}>{children}</body>
    </html>
  );
}
